Added necessary information in README to make it descriptive
sireclifford/admission-trial-code-review pull request #1
Opened 2022-05-30 18:32 UTC by sireclifford

Created html page

2022-05-30 18:35 UTC, sireclifford commented on README.md
>  👤 **Author2**
Remove second author since you are the only author

2022-05-30 18:37 UTC, sireclifford commented on index.html
> +  <script src="js/index.js"></script>
This is not necessary unless your project requires it. Adding unnecessary scripts to your work can slow down your website

2022-05-30 18:42 UTC, sireclifford reviewed
Well done on practising with what you have learnt so far.
Kindly follow the comments to make your work better.

Cheers!

2022-05-30 18:49 UTC, Kandy-Peter requested changes
Hi @sireclifford  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required Changes ♻️

- [ ] Please, ensure that the Pull Request you opened utilises the "Review changes" feature from GitHub instead of just competing the code. This helps users to know the PR state(Approved or requested changes). You can this short [Video](https://youtu.be/lSnbOtw4izI) for more understanding.
- [ ] I would also suggest you use summarised content as a message to the user who receives the review. You can pick an idea from mine(the look and the logic but not the content).

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-30 19:08 UTC, sireclifford commented
@Kandy-Peter I do not understand your second suggestion.

2022-06-03 23:24 UTC, sireclifford reviewed
Hi micronaut  , 

Well done getting this far.
However there are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @sireclifford   in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-06-03 23:31 UTC, Kakalanp commented
# STATUS: APPROVED :green_circle: 

### Your project is approved @sireclifford! :tada: 

There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :clinking_glasses: 

<img src="https://media.giphy.com/media/slOhiKAVFgwr6/giphy-downsized.gif" alt="almost there">

## Optional suggestions

- Excellent word choice [here](https://github.com/sireclifford/admission-trial-code-review/pull/1#pullrequestreview-989621273), but don't forget to [use those words everywhere](https://github.com/sireclifford/admission-trial-code-review/pull/1#discussion_r885028792)! 😉 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 01:14 UTC, merged